/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CityRouteImport } from './routes/$city'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminCalculatorsRouteImport } from './routes/admin.calculators'
import { Route as CityGalleryRouteImport } from './routes/$city_.gallery'
import { Route as CityContactRouteImport } from './routes/$city_.contact'
import { Route as CityBlogRouteImport } from './routes/$city_.blog'
import { Route as CityAboutRouteImport } from './routes/$city_.about'
import { Route as ApiPublicOzonWebhookRouteImport } from './routes/api/public/ozon-webhook'
import { Route as CityServicesSlugRouteImport } from './routes/$city_.services.$slug'
import { Route as CityBlogSlugRouteImport } from './routes/$city_.blog_.$slug'

const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalculatorsRoute = AdminCalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => AdminRoute,
} as any)
const CityGalleryRoute = CityGalleryRouteImport.update({
  id: '/$city_/gallery',
  path: '/$city/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CityContactRoute = CityContactRouteImport.update({
  id: '/$city_/contact',
  path: '/$city/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CityBlogRoute = CityBlogRouteImport.update({
  id: '/$city_/blog',
  path: '/$city/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CityAboutRoute = CityAboutRouteImport.update({
  id: '/$city_/about',
  path: '/$city/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOzonWebhookRoute = ApiPublicOzonWebhookRouteImport.update({
  id: '/api/public/ozon-webhook',
  path: '/api/public/ozon-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CityServicesSlugRoute = CityServicesSlugRouteImport.update({
  id: '/$city_/services/$slug',
  path: '/$city/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CityBlogSlugRoute = CityBlogSlugRouteImport.update({
  id: '/$city_/blog_/$slug',
  path: '/$city/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$city': typeof CityRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/$city/about': typeof CityAboutRoute
  '/$city/blog': typeof CityBlogRoute
  '/$city/contact': typeof CityContactRoute
  '/$city/gallery': typeof CityGalleryRoute
  '/admin/calculators': typeof AdminCalculatorsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/$city/blog/$slug': typeof CityBlogSlugRoute
  '/$city/services/$slug': typeof CityServicesSlugRoute
  '/api/public/ozon-webhook': typeof ApiPublicOzonWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$city': typeof CityRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/$city/about': typeof CityAboutRoute
  '/$city/blog': typeof CityBlogRoute
  '/$city/contact': typeof CityContactRoute
  '/$city/gallery': typeof CityGalleryRoute
  '/admin/calculators': typeof AdminCalculatorsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/$city/blog/$slug': typeof CityBlogSlugRoute
  '/$city/services/$slug': typeof CityServicesSlugRoute
  '/api/public/ozon-webhook': typeof ApiPublicOzonWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$city': typeof CityRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/$city_/about': typeof CityAboutRoute
  '/$city_/blog': typeof CityBlogRoute
  '/$city_/contact': typeof CityContactRoute
  '/$city_/gallery': typeof CityGalleryRoute
  '/admin/calculators': typeof AdminCalculatorsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/$city_/blog_/$slug': typeof CityBlogSlugRoute
  '/$city_/services/$slug': typeof CityServicesSlugRoute
  '/api/public/ozon-webhook': typeof ApiPublicOzonWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$city'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/$city/about'
    | '/$city/blog'
    | '/$city/contact'
    | '/$city/gallery'
    | '/admin/calculators'
    | '/admin/contacts'
    | '/admin/leads'
    | '/admin/orders'
    | '/admin/portfolio'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin/login'
    | '/api/chat'
    | '/blog/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/$city/blog/$slug'
    | '/$city/services/$slug'
    | '/api/public/ozon-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$city'
    | '/about'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/$city/about'
    | '/$city/blog'
    | '/$city/contact'
    | '/$city/gallery'
    | '/admin/calculators'
    | '/admin/contacts'
    | '/admin/leads'
    | '/admin/orders'
    | '/admin/portfolio'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin/login'
    | '/api/chat'
    | '/blog/$slug'
    | '/services/$slug'
    | '/admin'
    | '/$city/blog/$slug'
    | '/$city/services/$slug'
    | '/api/public/ozon-webhook'
  id:
    | '__root__'
    | '/'
    | '/$city'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/gallery'
    | '/$city_/about'
    | '/$city_/blog'
    | '/$city_/contact'
    | '/$city_/gallery'
    | '/admin/calculators'
    | '/admin/contacts'
    | '/admin/leads'
    | '/admin/orders'
    | '/admin/portfolio'
    | '/admin/services'
    | '/admin/testimonials'
    | '/admin_/login'
    | '/api/chat'
    | '/blog_/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/$city_/blog_/$slug'
    | '/$city_/services/$slug'
    | '/api/public/ozon-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityRoute: typeof CityRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  CityAboutRoute: typeof CityAboutRoute
  CityBlogRoute: typeof CityBlogRoute
  CityContactRoute: typeof CityContactRoute
  CityGalleryRoute: typeof CityGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  CityBlogSlugRoute: typeof CityBlogSlugRoute
  CityServicesSlugRoute: typeof CityServicesSlugRoute
  ApiPublicOzonWebhookRoute: typeof ApiPublicOzonWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city': {
      id: '/$city'
      path: '/$city'
      fullPath: '/$city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calculators': {
      id: '/admin/calculators'
      path: '/calculators'
      fullPath: '/admin/calculators'
      preLoaderRoute: typeof AdminCalculatorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$city_/gallery': {
      id: '/$city_/gallery'
      path: '/$city/gallery'
      fullPath: '/$city/gallery'
      preLoaderRoute: typeof CityGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city_/contact': {
      id: '/$city_/contact'
      path: '/$city/contact'
      fullPath: '/$city/contact'
      preLoaderRoute: typeof CityContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city_/blog': {
      id: '/$city_/blog'
      path: '/$city/blog'
      fullPath: '/$city/blog'
      preLoaderRoute: typeof CityBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city_/about': {
      id: '/$city_/about'
      path: '/$city/about'
      fullPath: '/$city/about'
      preLoaderRoute: typeof CityAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ozon-webhook': {
      id: '/api/public/ozon-webhook'
      path: '/api/public/ozon-webhook'
      fullPath: '/api/public/ozon-webhook'
      preLoaderRoute: typeof ApiPublicOzonWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city_/services/$slug': {
      id: '/$city_/services/$slug'
      path: '/$city/services/$slug'
      fullPath: '/$city/services/$slug'
      preLoaderRoute: typeof CityServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$city_/blog_/$slug': {
      id: '/$city_/blog_/$slug'
      path: '/$city/blog/$slug'
      fullPath: '/$city/blog/$slug'
      preLoaderRoute: typeof CityBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCalculatorsRoute: typeof AdminCalculatorsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalculatorsRoute: AdminCalculatorsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityRoute: CityRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  CityAboutRoute: CityAboutRoute,
  CityBlogRoute: CityBlogRoute,
  CityContactRoute: CityContactRoute,
  CityGalleryRoute: CityGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  CityBlogSlugRoute: CityBlogSlugRoute,
  CityServicesSlugRoute: CityServicesSlugRoute,
  ApiPublicOzonWebhookRoute: ApiPublicOzonWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
